name: BrandFarm
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  cupertino_icons: ^1.0.0

  # bloc pattern
  flutter_bloc: ^6.1.2
  bloc: ^6.1.1

  # adaptive design
  animated_text_kit: ^3.1.0
  adaptive_breakpoints: ^0.0.3

  # web/json
  http: ^0.13.2
  xml2json: ^5.1.0

  # material related
  equatable: ^1.2.6
  rxdart: ^0.26.0

  # fonts
  google_fonts: ^2.0.0
  font_awesome_flutter: ^8.11.0

  # widget
  flutter_speed_dial: ^2.1.1
  badges: ^1.1.6
  flutter_launcher_icons: ^0.9.0

  # locale related
  flutter_svg: ^0.22.0
  intl: ^0.16.1
  date_format: ^1.0.9

  # widget motions
  flutter_swiper: ^1.1.6
  dropdown_below: ^0.0.6
  shimmer: ^2.0.0
  animations: ^1.1.2
  scrollable_positioned_list: ^0.1.9

  # image/cache related
  path_provider: ^2.0.1
  multi_image_picker: 4.7.15
  image_picker: 0.7.4
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1

  # firebase related
  firebase_storage: ^8.0.5
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7

  # push notification
  firebase_messaging: ^9.1.3
  firebase_messaging_web: ^1.0.7

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  assets:
    - assets/
    - assets/weather_image/
    - assets/svg_icon/
    - assets/Journal/
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family:  BrandFarmIcons
      fonts:
        - asset: assets/icons/setting_icon.ttf
    - family: Weather
      fonts:
        - asset: assets/fonts/Weather/Weather.ttf
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
          weight: 800